services:
  teste2eDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://host.docker.internal:3000,http://host.docker.internal/,http://host.docker.internal,http://host.docker.internal:4000}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      teste2eDB:
        condition: service_healthy
    environment:
      DB_HOST: teste2eDB
    build: './server'
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src

  e2e:
    build:
      context: ./client
      dockerfile: Dockerfile.e2e
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
      - ./client/cypress:/app/cypress
    environment:
      - REACT_APP_GRAPHQL_API_URL=http://host.docker.internal:4000
      - CYPRESS_baseUrl=http://host.docker.internal:3000
